#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a xdman-Main state=floating

feh --bg-center ~/Videos/wallpaper/gintoki.png
polybar main &
#wal -R
#~/script/asus_kbd_light.sh
~/script/cleanfullscreen/cleanfullscreen
xsetroot -cursor_name left_ptr &
picom --experimental-backends
#cleanfullscreen
